apiVersion: v1
kind: Service
metadata:
  name: test-clb-service
  labels:
    app: test-bug-1208
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: test-bug-1208
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-bug-1208
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 8080
